name: Workflow Name

on:
  push:
    branches:
      - aca
    paths:
      - .github/workflows/aca.yml

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
```
